### ISSUE TITLE
Website is very mean to mobile browsers

### ISSUE THREAD

**Issue by williamg** [MellonHeads/mellonheads.github.io#6]
The implementation is optimized for >= 1200px monitors. If someone with mobile design experience wants to fix this that would be just lovely.

**Comment by RitwikGupta** [comment]
I would love to use Bootstrap with this. Since it's all custom CSS anyways, maybe we can import Bootstrap first and the custom CSS second, and then just add the proper classes to the divs.

**Comment by aroman** [comment]
@ThatGuyRussell I assume this is resolved now?
